$(document).ready(function(){
	$('#findName').hide();
	$('#message').hide();
	$('#menu').mouseenter(function(){
		$('#bottom').hide();
	});
	$('#menu').mouseleave(function(){
		$('#bottom').show();
	});
	$('#name').click(function(){
		$('#findName').show();
	});
	$('#findName').click(function(){
		$('#message').fadeIn();
	});
	$('#name2').click(function(){
		$('#message').fadeOut();
	});
});
